# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\InputPopup.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 260, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 30, 321, 216))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.LblFirst = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.LblFirst.setContentsMargins(0, 0, 0, 0)
        self.LblFirst.setObjectName("LblFirst")
        self.LblStudentID = QtWidgets.QLabel(self.formLayoutWidget)
        self.LblStudentID.setObjectName("LblStudentID")
        self.LblFirst.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.LblStudentID)
        self.txtStudentID = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtStudentID.setObjectName("txtStudentID")
        self.LblFirst.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtStudentID)
        self.LblFirst_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.LblFirst_2.setObjectName("LblFirst_2")
        self.LblFirst.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.LblFirst_2)
        self.txtFirst = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtFirst.setObjectName("txtFirst")
        self.LblFirst.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtFirst)
        self.LblLast = QtWidgets.QLabel(self.formLayoutWidget)
        self.LblLast.setObjectName("LblLast")
        self.LblFirst.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.LblLast)
        self.txtLast = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtLast.setObjectName("txtLast")
        self.LblFirst.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtLast)
        self.LblCourseName = QtWidgets.QLabel(self.formLayoutWidget)
        self.LblCourseName.setObjectName("LblCourseName")
        self.LblFirst.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.LblCourseName)
        self.txtCourseName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtCourseName.setObjectName("txtCourseName")
        self.LblFirst.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtCourseName)
        self.LblCRN = QtWidgets.QLabel(self.formLayoutWidget)
        self.LblCRN.setObjectName("LblCRN")
        self.LblFirst.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.LblCRN)
        self.txtCRN = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtCRN.setObjectName("txtCRN")
        self.LblFirst.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtCRN)
        self.LblTime = QtWidgets.QLabel(self.formLayoutWidget)
        self.LblTime.setObjectName("LblTime")
        self.LblFirst.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.LblTime)
        self.txtTime = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtTime.setObjectName("txtTime")
        self.LblFirst.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtTime)
        self.LblAttendance = QtWidgets.QLabel(self.formLayoutWidget)
        self.LblAttendance.setObjectName("LblAttendance")
        self.LblFirst.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.LblAttendance)
        self.cmbAttendance = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cmbAttendance.setObjectName("cmbAttendance")
        self.LblFirst.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cmbAttendance)
        self.LblDate = QtWidgets.QLabel(self.formLayoutWidget)
        self.LblDate.setObjectName("LblDate")
        self.LblFirst.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.LblDate)
        self.dateEdit = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.LblFirst.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.LblHeader = QtWidgets.QLabel(Dialog)
        self.LblHeader.setGeometry(QtCore.QRect(20, 10, 371, 16))
        self.LblHeader.setObjectName("LblHeader")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LblStudentID.setText(_translate("Dialog", "Student ID"))
        self.LblFirst_2.setText(_translate("Dialog", "First Name"))
        self.LblLast.setText(_translate("Dialog", "Last Name "))
        self.LblCourseName.setText(_translate("Dialog", "Course Name"))
        self.LblCRN.setText(_translate("Dialog", "Course CRN"))
        self.LblTime.setText(_translate("Dialog", "Class Time"))
        self.LblAttendance.setText(_translate("Dialog", "Attendance"))
        self.cmbAttendance.setProperty("Absent", _translate("Dialog", "Absent"))
        self.cmbAttendance.setProperty("Present", _translate("Dialog", "Present"))
        self.LblDate.setText(_translate("Dialog", "Date"))
        self.LblHeader.setText(_translate("Dialog", "Input Attendance Information"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
